version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ../src:/var/www
      - ./.env:/var/www/.env
    networks:
      - proxy
  nginx:
    image: nginx:1.23-alpine
    environment:
      VIRTUAL_HOST: ${DOMAIN_NAME:-localhost}
      LETSENCRYPT_HOST: ${DOMAIN_NAME:-localhost}
      VIRTUAL_PORT: ${VIRTUAL_PORT:-80}
    container_name: cookspot-nginx
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ../src:/var/www
      - ./nginx:/etc/nginx/conf.d
    networks:
      - proxy
  db:
    image: mysql:8.0
    container_name: cookspot-db
    volumes:
      - ./storage/mysql:/var/lib/mysql
      - ./dump:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    ports:
      - 3306:3306
    networks:
      - proxy

networks:
  proxy:
    name: proxy
    external: true