version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: cookspot-app
    restart: always
    volumes:
      - ../src:/var/www
      - ./.env:/var/www/.env
  nginx:
    image: nginx:1.23-alpine
    container_name: cookspot-nginx
    restart: always
    volumes:
      - ../src:/var/www
      - ./nginx:/etc/nginx/conf.d
  db:
    image: mysql:8.0
    container_name: cookspot-db
    volumes:
      - ./storage/mysql:/var/lib/mysql
      - ./dump:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    ports:
      - 3306:3306