version: '3.8'

services:
  app:
    env_file:
      - .env
      - .env.local
    networks:
      - proxy
  nginx:
    environment:
      VIRTUAL_HOST: ${DOMAIN_NAME:-localhost}
      LETSENCRYPT_HOST: ${DOMAIN_NAME:-localhost}
      VIRTUAL_PORT: ${VIRTUAL_PORT:-80}
    networks:
      - proxy
  db:
    networks:
      - proxy

networks:
  proxy:
    name: proxy
    external: true